#!/bin/sh

fetch() {
	return
	FILENAME="nano-4.3.tar.xz"
	wget -O "$CACHE_DIR/$FILENAME" https://www.nano-editor.org/dist/v4/$FILENAME
	tar xfv "$CACHE_DIR/$FILENAME" -C "$CACHE_DIR"
}

build() {
	cd "$CACHE_DIR/nano-4.3"
}
